### PR TITLE
Un-Eject Create-React-App

### PR DESCRIPTION
**Pull request by jonathanhudak**
@shiftsave 
This should un-eject us and get us back on with create-react-app. Huzzah!

You can still develop with stylus by running `yarn start dev-stylus`, so this shouldn't disrupt our css workflow.

`yarn start` will compile the stylus files into Main.css which will be imported.

pull this down and test it out for yourself. I was able to retain the relative import paths which is super awesome! https://github.com/facebookincubator/create-react-app/issues/581

We should put out another PR using styled-components. I think that is the way forward for CSS in general. Pre-processing CSS is not as useful as it once was.

### CODE REVIEW

**Comment by shiftsave** [comment]
@hudakdidit aawesome! I actually already started porting over our styles to styled-components, gonna be a bit slow, but once we get up and running should be fine.

**Comment by jonathanhudak** [comment]
@shiftsave were you able to test this? It work for you?

**Comment by jonathanhudak** [comment]
@shiftsave hey could I check this in, have you tried it?

**Comment by shiftsave** [comment]
@hudakdidit it did work back when I tried it, I'll fix conflicts and test again next

**Comment by jonathanhudak** [comment]
@shiftsave I've resolved the merge conflicts. Please test when you are able and let's merge this

**Comment by shiftsave** [comment]
Oh awesome @hudakdidit I'll take a look tonight

**Comment by shiftsave** [comment]
@hudakdidit Getting this
screen shot 2017-10-19 at 1 48 45 pm

I also got a `app-config.json` not found but assumed this was just the `.env.json` file right?

**Comment by jonathanhudak** [comment]
@shiftsave try again. I just pushed an update. I also updated the readme directions for `app-config.json` I can't quite remember but I needed to move the config to the `src` directory. So just run `cp .env.json src/app-config.json`

**Comment by jonathanhudak** [comment]
Oh I had to move this because to get the relative imports working I had to add the .env file to default imports from `src`

**Comment by shiftsave** [comment]
@hudakdidit this loads and everything looks 👍

**Pull request merged**
